name: mjn_liquid_ui
description: Native-inspired Liquid Glass UI components for Flutter, focused on iOS SwiftUI and UIKit.
version: 0.1.9
repository: https://github.com/Gerafftes/mjn_liquid_ui
issue_tracker: https://github.com/Gerafftes/mjn_liquid_ui/issues

environment:
  sdk: ^3.9.2
  flutter: ">=3.27.0"

topics:
  - flutter
  - ios
  - cupertino
  - liquid-glass
  - ui

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AppleLiquidTabbarPlugin
